### ISSUE TITLE
练习册

### ISSUE THREAD

**Issue by dengwanc** [dengwanc/dengwanc.github.io#19]
* 如果需要在终端里操作文件内容，使用 vim
* 尽可能的用英文输入/表达
* 在写代码之前尽可能的设计好考虑到多种情况，参考俄罗斯程序员的故事
* 注重高效解决问题，而不是为了自己的学习

**Comment by zhangyachen** [comment]
俄罗斯程序员啥故事

**Comment by dengwanc** [comment]
现在纸上写代码，设计好了之后，上机写，他们能做到很少的错误。
